### ISSUE TITLE
ff logs not returning any logs

### ISSUE THREAD

**Issue by matthew1001** [hyperledger/firefly-cli#214]
Issuing `ff logs <stack name>` doesn't output any logs, it simply prints "getting logs..." and returns.

Running the equivalent docker compose command manually (`docker compose -p <stack-name> logs`) correctly outputs logs from all of the running containers to stdout.

**Comment by matthew1001** [comment]
Not sure why I didn't notice when raising this issue, but it looks like `ff logs <stack name>` is designed to only output logs to stdout if `--verbose` is specified. It looks like this was an explicit change made in commit https://github.com/hyperledger/firefly-cli/commit/ee143951f571743ce9a5fc19f0f3903069b4fa4f @nguyer I'm happy to close this if that's the intended behaviour, but not specifying --verbose doesn't return anything so there might be an argument for dropping the requirement to specify it?

**Comment by nguyer** [comment]
Thanks for finding this @matthew1001. That was definitely an unintentional side effect of that change.

**Comment by matthew1001** [comment]
OK no probs, I'm happy to put it back to the original behaviour and submit a PR to close this one off.
