### ISSUE TITLE
Error: reading image "ghcr.io/hyperledger/firefly:latest"

### ISSUE THREAD

**Issue by GarethWGSMA** [hyperledger/firefly-cli#228]
Hi guys,

I'm obviously doing something very wrong ... I can't even create a basic Firflys tack. I've installed docker, it apprently uses wsl2 and run's the hello world program.

When I try to follow the instructions to setup the firefly stack I get "Error: reading image "ghcr.io/hyperledger/firefly:latest"
![image](https://user-images.githubusercontent.com/110228888/202698300-088286c7-ba24-4604-a236-8d8882eee51d.png)

Any help would be great. Thanks!

**Comment by nguyer** [comment]
Hi @GarethWGSMA. Sorry you're experiencing this. This error means that your computer was unable to reach GitHub's container image repository. Unfortunately there is nothing we as project maintainers can do to fix that. You could try a different network connection, or a different computer.
