### ISSUE TITLE
Recipients don't appear on sandbox homescreen, for sending private messages

### ISSUE THREAD

**Issue by tefamack** [hyperledger/firefly-cli#242]
I have created a stack of 3 nodes, I got correctly the sandbox and web ui for each member, although I cannot send private messages, because there are no recipients in the list (where should be the other nodes of the stack)

**Comment by nguyer** [comment]
Hi @tefamack. I am unable to reproduce this behavior on my own machine. Can you share the following information?

- What version of the FireFly CLI are you running? You can run `ff version` to check
- What was the full `ff init` command that you used to create your stack, and any interactive inputs?

**Comment by tefamack** [comment]
Hey @nguyer thanks for the response!
About the information you ask:

- FF version

  "Version": "1.1.2",
  "Commit": "8b462fff760e1c7cc1d11c3ddb34638c094b0f2e",
  "Date": "2022-11-17T21:16:50Z",
  "License": "Apache-2.0"

- I used the following commands (actually with sudo previously)
ff init model 3
ff upgrade model
ff start model

These were the webs members:

Web UI for member '0': http://127.0.0.1:5000/ui
Sandbox UI for member '0': http://127.0.0.1:5109

Web UI for member '1': http://127.0.0.1:5001/ui
Sandbox UI for member '1': http://127.0.0.1:5209

Web UI for member '2': http://127.0.0.1:5002/ui
Sandbox UI for member '2': http://127.0.0.1:5309

Also, when I run the sandbox ui, there is a message that says "Fetch failed: e is undefined"... probably the problem is related to that message, but I'm not sure what it actually means. 

THANKS!!

**Comment by nguyer** [comment]
Ah. So using `sudo` is highly likely to cause problems.

Also, the upgrade command in that version of the FireFly CLI has some issues, and FireFly stacks created with that version or earlier that use SQLite as the database likely cannot be upgraded with the upgrade command.

I would suggest 1) Upgrading to the latest FireFly CLI and 2) Creating a new FireFly stack with that version (which will be upgradable in the future)

**Comment by nguyer** [comment]
There was a new version of the CLI that was just released a few days ago, so maybe you ran that command before then.

Also, there are some recommended best practices in the Docker docks for running without `sudo` here: https://docs.docker.com/engine/install/linux-postinstall/

**Comment by tefamack** [comment]
thanks @nguyer !!
