### ISSUE TITLE
looking for help for setup evm connect only connect to hyperledger besu 

### ISSUE THREAD

**Issue by elohffa** [hyperledger/firefly-cli#274]
could u let me know how can I config for only the firefly to connect my hyperledger besu rpc endpoint ? my besu endpoint is a in remote . could u let me know anyone can help

**Comment by nguyer** [comment]
Hi @elohffa. I or other community members would be happy to help you out with this over in the #firefly channel in the [Hyperledger Discord server](https://discord.com/invite/hyperledger). We use GitHub to track bugs or specific work items and not for general support. Thanks!
