### ISSUE TITLE
Environment deletion fails with FF CLI built from `main`

### ISSUE THREAD

**Issue by peterbroadhurst** [hyperledger/firefly-cli#295]
This is a bit challenging in a migration scenario, as I would expect the normal flow is:
- Install new `ff`
- Find you need to delete your old dev env
- Run `ff rm` (currently fails)
- Re-run `ff init`

```
./ff/ff rm -f dev                    
deleting FireFly stack 'dev'... Error: Error: No such volume: dev_geth

Usage:
  ff remove <stack_name> [flags]

Aliases:
  remove, rm

Flags:
  -f, --force   Remove the stack without prompting for confirmation
  -h, --help    help for remove

Global Flags:
      --ansi string   control when to print ANSI control characters ("never"|"always"|"auto") (default "auto")
  -v, --verbose       verbose log output

```

**Comment by peterbroadhurst** [comment]
Ah - so I've realized the `main` branch of the CLI also doesn't use the 1.3 RC by default either... so I ended up with a broken environment when I created a new environment as well - guess not strictly related:

```
FF00184: Database migration failed: FF00184: Database migration failed: unable to open database file: no such file or directory
```

**Comment by peterbroadhurst** [comment]
Hmmmn, well I also can't create a new environment I just created...

**Comment by peterbroadhurst** [comment]
```
➜  firefly-cli git:(main) ./ff/ff init --multiparty=false gw2 1
initializing new FireFly stack...
Stack 'gw2' created!
To start your new stack run:

ff start gw2

Your docker compose file for this stack can be found at: /Users/pbroadhurst/.firefly/stacks/gw2/docker-compose.yml

➜  firefly-cli git:(main) ./ff/ff rm gw2                       
WARNING: This will completely remove your stack and all of its data. Are you sure this is what you want to do?
completely delete FireFly stack 'gw2' [y/N] y
deleting FireFly stack 'gw2'... Error: Error: No such volume: gw2_geth

Usage:
  ff remove <stack_name> [flags]

Aliases:
  remove, rm

Flags:
  -f, --force   Remove the stack without prompting for confirmation
  -h, --help    help for remove

Global Flags:
      --ansi string   control when to print ANSI control characters ("never"|"always"|"auto") (default "auto")
  -v, --verbose       verbose log output

Error: Error: No such volume: gw2_geth
```

**Comment by peterbroadhurst** [comment]
Ok - with a bit more testing, I thinks the scope of the issue is:
- v1.2 environments
- v1.3 environments that _haven't been intialized_

**Comment by nguyer** [comment]
Thanks for opening this! I think I have seen this issue as well. I thought I fixed it, but maybe it was a similar but slightly different issue.

For background we used to swallow a lot of errors, and when we added the linter it wasn't a big fan of that. Making the linter happy ended up with some errors that still _should have been swallowed_ (or at least logged) getting returned all the way up. This was one of those. Should be an easy fix. I'll open a PR for it.

**Comment by nguyer** [comment]
@peterbroadhurst Are you sure you are running the latest code in main? I think this existing check should allow this condition to not return the error:
https://github.com/hyperledger/firefly-cli/blob/3679daf0650b0fa1870b86945603f2b2f71577d6/internal/stacks/stack_manager.go#L707-L709
