### ISSUE TITLE
Error: failed to find installed chaincode

### ISSUE THREAD

**Issue by aleleo1998** [hyperledger/firefly-cli#297]
any solutions?
i did 
1) peer lifecycle chaincode package -p . --label asset_transfer ./asset_transfer.zip
2) ff deploy fabric dev asset_transfer.zip firefly asset_transfer 1.0

installing chaincode
querying installed chaincode
Error: failed to find installed chaincode
Usage:
  ff deploy fabric <stack_name> <chaincode_package> <channel> <chaincodeName> <version> [flags]

Flags:
  -h, --help   help for fabric

Global Flags:
      --ansi string   control when to print ANSI control characters ("never"|"always"|"auto") (default "auto")
  -v, --verbose       verbose log output

Error: failed to find installed chaincode

My peer version:
peer:
 Version: v2.5.6
 Commit SHA: 61fad7b
 Go version: go1.21.6
 OS/Arch: linux/amd64
 Chaincode:
  Base Docker Label: org.hyperledger.fabric
  Docker Namespace: hyperledger

my go version:
go version go1.14 linux/amd64

**Comment by nguyer** [comment]
Thanks for reporting this @aleleo1998. I also recently ran into this issue and it should be fixed in https://github.com/hyperledger/firefly-cli/pull/300
