### ISSUE TITLE
firefly init fabric failed

### ISSUE THREAD

**Issue by zhangte3** [hyperledger/firefly-cli#316]
When I started to init the fabric and got below errors. My firefly cli version is as below.

{
  "Version": "1.3.1-rc1",
  "Commit": "a488f05eb292381ca77236c8dafa956d7f77ae44",
  "Date": "2024-07-17T14:21:29Z",
  "License": "Apache-2.0"
}

Error: stat /root/.firefly/stacks/<stackname>/docker-compose.yml: no such file or directory

**Comment by zhangte3** [comment]
> weird.... the stack name is not present in that path
> 
> What command did you use?
The below is my command
ff init fabric gsbndev 3 -v
initializing new FireFly stack...
Error: stat /home/gsbn/.firefly/stacks/gsbndev/docker-compose.yml: no such file or directory

**Comment by EnriqueL8** [comment]
That worked for me - what machine are you using? are you on linux? 

What permissions does your file system give  the CLI?

**Comment by zhangte3** [comment]
> That worked for me - what machine are you using? are you on linux?
> 
> What permissions does your file system give the CLI?

I run as root or user under docker group will get the same error. Don't know whether need extra permission for it.
