### ISSUE TITLE
Create homebrew formula for ff-cli

### ISSUE THREAD

**Issue by shorsher** [hyperledger/firefly-cli#59]
It would be awesome to have the cli distributed & managed through homebrew (and other package managers), so users do not need to manually upgrade versions, etc.

**Comment by hfuss** [comment]
For doing so, Goreleaser is likely our best bet: https://github.com/goreleaser/goreleaser

Here's a guide we can follow for integrating Goreleaser into a GHA workflow: https://goreleaser.com/ci/actions/

**Comment by dwertent** [comment]
This PR will close the issue once merged: https://github.com/Homebrew/homebrew-core/pull/181415

To install:
```
brew install firefly
```

**Note:** I noticed that the executable is currently named ff and this is hardcoded in some of the help messages. I'll be submitting a follow-up PR next week to make the executable name configurable at build time, similar to how the version is handled.

**Comment by EnriqueL8** [comment]
@dwertent I recommend we rename it to firefly-cli

**Comment by dwertent** [comment]
@EnriqueL8 we can close this issue

**Comment by EnriqueL8** [comment]
Awesome stuff, before I close it going to assign it to you
