### ISSUE TITLE
Add checks to make sure docker and docker-compose are set up correctly

### ISSUE THREAD

**Issue by nguyer** [hyperledger/firefly-cli#93]
On setting up a new dev environment it's easy to miss steps, especially if you're in a hurry, or if you're like me and think you know what you're doing without reading the instructions. For example, if you install `docker` but not `docker-compose` (on Linux they're two different packages), some things will work, but other things will not. It would be great to have some checks to make sure prerequisites are in place before starting to try to use docker or docker-compose. If things are not set up correctly, it would be nice for the CLI to print out a helpful error message. Right now, if docker-compose is not installed, usually the error that gets printed is very cryptic.

The docker daemon not running in the background is another common issue that people sometimes run into.

Lastly, the current user might not have permission to run docker commands without `sudo` if they're not in the right group. It would be great if the CLI could run quick pre-check to make sure all these things are set up correctly. I think this would really help new devs setting up their environment for the first time.

**Comment by rakshita-kaulgud** [comment]
Can I be assigned this issue? (Working on this as a part od GHC OSD)
