### ISSUE TITLE
firefly logs command is broken

### ISSUE THREAD

**Issue by meeramn** [hyperledger/firefly-cli#96]
firefly logs command is broken. Please find the detailed error below.

```
ff logs dev1
getting logs...
Define and run multi-container applications with Docker.

Usage:
  docker-compose [-f <arg>...] [options] [COMMAND] [ARGS...]
  docker-compose -h|--help
```

**Comment by nguyer** [comment]
Thanks for reporting this! This is definitely not what we expect to see. I'll take a look to figure out what's going on.
